stages:
  - build
  - unitTest
  - integerationTest

before_script:
  - python -V
  - pip install -r requirement.txt


build:
  image: python:3.6.9-stretch
  stage: build
  script:
    - echo "Building"
    - pip install -r requirement.txt
    - ./manage.py makemigrations
    - ./manage.py migrate

unitTest:
  image: python:3.7.2-stretch
  stage: unitTest
  script:
    - echo "Testing"
    - ./manage.py test

integerationTest:
  image: python:3.7.2-stretch
  stage: integerationTest
  script:
    - echo "Testing"
    - ./manage.py test

