# Generated by Django 2.2.7 on 2019-11-29 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jalas_back', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='participant',
        ),
        migrations.AddField(
            model_name='meeting',
            name='date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='تاریخ'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='endTime',
            field=models.TimeField(blank=True, default=None, null=True, verbose_name='زمان اتمام'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='startTime',
            field=models.TimeField(blank=True, default=None, null=True, verbose_name='زمان شروع'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'در انتظار اتاق'), (2, 'رزرو کامل'), (3, 'برگزار شده')], default=None, null=True, verbose_name='وضعیت جلسه'),
        ),
        migrations.CreateModel(
            name='SelectUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selects', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voted', to='jalas_back.Select')),
                ('users', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voted', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('text', models.TextField(verbose_name='متن')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='jalas_back.Meeting')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to='jalas_back.Meeting')),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participateIn', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='select',
            name='poll',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='selects', to='jalas_back.Poll'),
        ),
    ]
