# Generated by Django 2.2.7 on 2019-11-30 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jalas_back', '0002_auto_20191129_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selectuser',
            old_name='selects',
            new_name='select',
        ),
        migrations.RenameField(
            model_name='selectuser',
            old_name='users',
            new_name='user',
        ),
    ]
