# Generated by Django 2.2.7 on 2019-11-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jalas_back', '0003_auto_20191130_0712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='select',
            name='text',
        ),
        migrations.AddField(
            model_name='select',
            name='agreement',
            field=models.IntegerField(choices=[(1, 'خیر'), (2, 'بله')], null=True, verbose_name='نظر'),
        ),
    ]
