# Generated by Django 2.2.7 on 2019-11-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jalas_back', '0004_auto_20191130_0718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='select',
            name='agreement',
        ),
        migrations.AddField(
            model_name='select',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='متن'),
        ),
        migrations.AddField(
            model_name='selectuser',
            name='agreement',
            field=models.IntegerField(choices=[(1, 'خیر'), (2, 'بله')], null=True, verbose_name='نظر'),
        ),
    ]
