# Generated by Django 2.2.7 on 2019-11-30 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jalas_back', '0005_auto_20191130_0750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='select',
            name='text',
        ),
        migrations.AddField(
            model_name='select',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 11, 30, 14, 26, 7, 694067), verbose_name='تاریخ'),
        ),
        migrations.AddField(
            model_name='select',
            name='endTime',
            field=models.TimeField(default=datetime.time(14, 26, 7, 694132), verbose_name='زمان اتمام'),
        ),
        migrations.AddField(
            model_name='select',
            name='startTime',
            field=models.TimeField(default=datetime.time(14, 26, 7, 694108), verbose_name='زمان شروع'),
        ),
    ]
