# Generated by Django 2.2.7 on 2019-11-30 15:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jalas_back', '0006_auto_20191130_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='select',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='select',
            name='endTime',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='زمان اتمام'),
        ),
        migrations.AlterField(
            model_name='select',
            name='startTime',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='زمان شروع'),
        ),
    ]
