# Generated by Django 2.2.7 on 2019-12-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jalas_back', '0009_meeting_iscancel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'در انتظار اتاق'), (2, 'رزرو کامل'), (3, 'برگزار شده'), (4, 'لغو شده')], default=None, null=True, verbose_name='وضعیت جلسه'),
        ),
    ]
