# Generated by Django 2.2.7 on 2019-12-02 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jalas_back', '0011_reservationtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationtime',
            name='meeting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserveDuration', to='jalas_back.Meeting', unique=True),
        ),
    ]
