# Generated by Django 3.0.1 on 2020-01-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrange_meeting', models.BooleanField(default=False, verbose_name='arrange_meeting')),
                ('add_option', models.BooleanField(default=False, verbose_name='add_option')),
                ('new_vote', models.BooleanField(default=False, verbose_name='new_vote')),
                ('remove_option', models.BooleanField(default=False, verbose_name='add_option')),
                ('add_new_participant', models.BooleanField(default=False, verbose_name='add_new_participant')),
                ('close_poll', models.BooleanField(default=False, verbose_name='close_poll')),
                ('close_meeting', models.BooleanField(default=False, verbose_name='close_meeting')),
            ],
        ),
    ]
