# Generated by Django 3.0.1 on 2020-01-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0002_configuration_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='create_poll',
            field=models.BooleanField(default=False, verbose_name='create_poll'),
        ),
    ]
