# Generated by Django 2.2.7 on 2019-12-10 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('text', models.TextField(verbose_name='متن')),
                ('date', models.DateField(blank=True, default=None, null=True, verbose_name='تاریخ')),
                ('startTime', models.TimeField(blank=True, default=None, null=True, verbose_name='زمان شروع')),
                ('endTime', models.TimeField(blank=True, default=None, null=True, verbose_name='زمان اتمام')),
                ('status', models.IntegerField(blank=True, choices=[(1, 'در انتظار اتاق'), (2, 'رزرو کامل'), (3, 'برگزار شده'), (4, 'لغو شده')], default=1, null=True, verbose_name='وضعیت جلسه')),
                ('room', models.IntegerField(blank=True, default=None, null=True, verbose_name='شماره اتاق')),
                ('isCancel', models.BooleanField(blank=True, default=False, verbose_name='وضعیت لغو')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
