# Generated by Django 2.2.7 on 2019-12-11 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_auto_20191211_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectuser',
            name='select',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='voted', to='poll.Select', unique=True),
        ),
        migrations.AlterField(
            model_name='selectuser',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='voted', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
