# Generated by Django 2.2.7 on 2019-12-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_auto_20191211_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectuser',
            name='name',
            field=models.CharField(default=None, max_length=100, unique=True, verbose_name='نام شرکت کننده'),
        ),
    ]
