# Generated by Django 2.2.7 on 2019-12-14 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_selectuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectuser',
            name='name',
            field=models.CharField(default=None, max_length=100, verbose_name='نام شرکت کننده'),
        ),
        migrations.AlterField(
            model_name='selectuser',
            name='select',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='voted', to='poll.Select'),
        ),
        migrations.AlterField(
            model_name='selectuser',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='voted', to=settings.AUTH_USER_MODEL),
        ),
    ]
