# Generated by Django 2.2.7 on 2019-12-14 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0006_auto_20191214_1111'),
        ('poll', '0006_auto_20191214_0959'),
    ]

    operations = [
    ]
