# Generated by Django 3.0.1 on 2020-01-07 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0008_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
