# Generated by Django 3.0.1 on 2020-01-09 13:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0011_auto_20200108_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='date_close',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='تاریخ'),
        ),
    ]
