# Generated by Django 3.0.1 on 2020-01-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0012_auto_20200109_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='status',
            field=models.BooleanField(default=False, verbose_name='وضعیت رای\u200cگیری'),
        ),
    ]
