# Generated by Django 3.0.1 on 2020-01-10 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0011_auto_20200108_1352'),
        ('poll', '0012_auto_20200109_1332'),
    ]

    operations = [
    ]
