# Generated by Django 3.0.1 on 2020-01-10 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0013_merge_20200110_1020'),
        ('poll', '0013_auto_20200110_1518'),
    ]

    operations = [
    ]
