# Generated by Django 2.2.7 on 2019-12-10 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservationStartTime', models.TimeField(blank=True, default=None, null=True, verbose_name='زمان شروع')),
                ('reservationEndTime', models.TimeField(blank=True, default=None, null=True, verbose_name='زمان پایان')),
                ('meeting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserveDuration', to='meeting.Meeting', unique=True)),
            ],
        ),
    ]
