# Generated by Django 3.0.1 on 2019-12-28 09:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0002_auto_20191224_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Throghput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
