# Generated by Django 3.0.1 on 2019-12-28 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0003_throghput'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Throghput',
            new_name='Throughput',
        ),
    ]
