# Generated by Django 3.0.1 on 2019-12-28 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0005_response'),
        ('logger', '0002_auto_20191224_1452'),
    ]

    operations = [
    ]
