# Generated by Django 3.0.1 on 2019-12-28 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0005_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='throughput',
            name='create_date',
            field=models.FloatField(default=0.0),
        ),
    ]
