# Generated by Django 3.0.1 on 2019-12-28 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0006_merge_20191228_1049'),
        ('logger', '0006_auto_20191228_1104'),
    ]

    operations = [
    ]
